#!/bin/sh

export VIMRUNTIME=$APPDIR/share/nvim/runtime/
export XDG_CONFIG_DIRS=$XDG_CONFIG_DIRS:$APPDIR/etc/

while true; do
  case "$1" in
    --fork_config ) FORK=true; shift ;;
    -- ) shift; break ;;
    * ) break ;;
  esac
done

#if [ "$FORK" -ne "" ] && [ ! -d ~/.config/nvim ]; then
#     cp $APPDIR/etc/nvim ~/.config/nvim -a
#fi

exec $APPDIR/bin/nvim $@
